package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssortmentTypeDescription generated by hbm2java
 */
@Entity
@Table(name = "ASSORTMENT_TYPE_DESCRIPTION")
public class AssortmentTypeDescription implements java.io.Serializable {

	private int kod;
	private Integer kodAssortmentType;
	private String name;
	private Integer kodOld;
	private Short assemblyEditType;

	public AssortmentTypeDescription() {
	}

	public AssortmentTypeDescription(int kod) {
		this.kod = kod;
	}

	public AssortmentTypeDescription(int kod, Integer kodAssortmentType,
			String name, Integer kodOld, Short assemblyEditType) {
		this.kod = kod;
		this.kodAssortmentType = kodAssortmentType;
		this.name = name;
		this.kodOld = kodOld;
		this.assemblyEditType = assemblyEditType;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "KOD_ASSORTMENT_TYPE")
	public Integer getKodAssortmentType() {
		return this.kodAssortmentType;
	}

	public void setKodAssortmentType(Integer kodAssortmentType) {
		this.kodAssortmentType = kodAssortmentType;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "KOD_OLD")
	public Integer getKodOld() {
		return this.kodOld;
	}

	public void setKodOld(Integer kodOld) {
		this.kodOld = kodOld;
	}

	@Column(name = "ASSEMBLY_EDIT_TYPE")
	public Short getAssemblyEditType() {
		return this.assemblyEditType;
	}

	public void setAssemblyEditType(Short assemblyEditType) {
		this.assemblyEditType = assemblyEditType;
	}

}
