package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssortmentDescription generated by hbm2java
 */
@Entity
@Table(name = "ASSORTMENT_DESCRIPTION")
public class AssortmentDescription implements java.io.Serializable {

	private int kod;
	private Integer kodAssortment;
	private Integer kodAssortmentTypeDescription;
	private String name;

	public AssortmentDescription() {
	}

	public AssortmentDescription(int kod) {
		this.kod = kod;
	}

	public AssortmentDescription(int kod, Integer kodAssortment,
			Integer kodAssortmentTypeDescription, String name) {
		this.kod = kod;
		this.kodAssortment = kodAssortment;
		this.kodAssortmentTypeDescription = kodAssortmentTypeDescription;
		this.name = name;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "KOD_ASSORTMENT")
	public Integer getKodAssortment() {
		return this.kodAssortment;
	}

	public void setKodAssortment(Integer kodAssortment) {
		this.kodAssortment = kodAssortment;
	}

	@Column(name = "KOD_ASSORTMENT_TYPE_DESCRIPTION")
	public Integer getKodAssortmentTypeDescription() {
		return this.kodAssortmentTypeDescription;
	}

	public void setKodAssortmentTypeDescription(
			Integer kodAssortmentTypeDescription) {
		this.kodAssortmentTypeDescription = kodAssortmentTypeDescription;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
