package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClassTemp generated by hbm2java
 */
@Entity
@Table(name = "CLASS_TEMP")
public class ClassTemp implements java.io.Serializable {

	private ClassTempId id;

	public ClassTemp() {
	}

	public ClassTemp(ClassTempId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "kod", column = @Column(name = "KOD", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "NAME")),
			@AttributeOverride(name = "note", column = @Column(name = "NOTE")),
			@AttributeOverride(name = "dateWrite", column = @Column(name = "DATE_WRITE", length = 19)) })
	public ClassTempId getId() {
		return this.id;
	}

	public void setId(ClassTempId id) {
		this.id = id;
	}

}
