package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassTempId generated by hbm2java
 */
@Embeddable
public class ClassTempId implements java.io.Serializable {

	private int kod;
	private String name;
	private String note;
	private Date dateWrite;

	public ClassTempId() {
	}

	public ClassTempId(int kod) {
		this.kod = kod;
	}

	public ClassTempId(int kod, String name, String note, Date dateWrite) {
		this.kod = kod;
		this.name = name;
		this.note = note;
		this.dateWrite = dateWrite;
	}

	@Column(name = "KOD", nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassTempId))
			return false;
		ClassTempId castOther = (ClassTempId) other;

		return (this.getKod() == castOther.getKod())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())))
				&& ((this.getDateWrite() == castOther.getDateWrite()) || (this
						.getDateWrite() != null
						&& castOther.getDateWrite() != null && this
						.getDateWrite().equals(castOther.getDateWrite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKod();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result
				+ (getDateWrite() == null ? 0 : this.getDateWrite().hashCode());
		return result;
	}

}
