package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commodity generated by hbm2java
 */
@Entity
@Table(name = "COMMODITY")
public class Commodity implements java.io.Serializable {

	private int kod;
	private Integer assortmentKod;
	private Integer quantity;
	private Integer operationKod;
	private Date dateInOut;
	private Integer pointKod;
	private String note;
	private Integer reminderKod;
	private Date dateWrite;
	private Integer serialKod;
	private BigDecimal discont;
	private Short showPaperWarranty;
	private Short showPaperCommodity;

	public Commodity() {
	}

	public Commodity(int kod) {
		this.kod = kod;
	}

	public Commodity(int kod, Integer assortmentKod, Integer quantity,
			Integer operationKod, Date dateInOut, Integer pointKod,
			String note, Integer reminderKod, Date dateWrite,
			Integer serialKod, BigDecimal discont, Short showPaperWarranty,
			Short showPaperCommodity) {
		this.kod = kod;
		this.assortmentKod = assortmentKod;
		this.quantity = quantity;
		this.operationKod = operationKod;
		this.dateInOut = dateInOut;
		this.pointKod = pointKod;
		this.note = note;
		this.reminderKod = reminderKod;
		this.dateWrite = dateWrite;
		this.serialKod = serialKod;
		this.discont = discont;
		this.showPaperWarranty = showPaperWarranty;
		this.showPaperCommodity = showPaperCommodity;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "ASSORTMENT_KOD")
	public Integer getAssortmentKod() {
		return this.assortmentKod;
	}

	public void setAssortmentKod(Integer assortmentKod) {
		this.assortmentKod = assortmentKod;
	}

	@Column(name = "QUANTITY")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "OPERATION_KOD")
	public Integer getOperationKod() {
		return this.operationKod;
	}

	public void setOperationKod(Integer operationKod) {
		this.operationKod = operationKod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_IN_OUT", length = 10)
	public Date getDateInOut() {
		return this.dateInOut;
	}

	public void setDateInOut(Date dateInOut) {
		this.dateInOut = dateInOut;
	}

	@Column(name = "POINT_KOD")
	public Integer getPointKod() {
		return this.pointKod;
	}

	public void setPointKod(Integer pointKod) {
		this.pointKod = pointKod;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "REMINDER_KOD")
	public Integer getReminderKod() {
		return this.reminderKod;
	}

	public void setReminderKod(Integer reminderKod) {
		this.reminderKod = reminderKod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

	@Column(name = "SERIAL_KOD")
	public Integer getSerialKod() {
		return this.serialKod;
	}

	public void setSerialKod(Integer serialKod) {
		this.serialKod = serialKod;
	}

	@Column(name = "DISCONT", precision = 15)
	public BigDecimal getDiscont() {
		return this.discont;
	}

	public void setDiscont(BigDecimal discont) {
		this.discont = discont;
	}

	@Column(name = "SHOW_PAPER_WARRANTY")
	public Short getShowPaperWarranty() {
		return this.showPaperWarranty;
	}

	public void setShowPaperWarranty(Short showPaperWarranty) {
		this.showPaperWarranty = showPaperWarranty;
	}

	@Column(name = "SHOW_PAPER_COMMODITY")
	public Short getShowPaperCommodity() {
		return this.showPaperCommodity;
	}

	public void setShowPaperCommodity(Short showPaperCommodity) {
		this.showPaperCommodity = showPaperCommodity;
	}

}
