package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommodityReturn generated by hbm2java
 */
@Entity
@Table(name = "COMMODITY_RETURN")
public class CommodityReturn implements java.io.Serializable {

	private int kod;
	private Integer assortmentKod;
	private Integer quantity;
	private Integer operationKod;
	private Integer pointKod;
	private Date dateSells;
	private Date dateUpdate;
	private Short showPaperWarranty;
	private Integer showPaperCommodity;
	private Double amount;
	private Integer serialKod;

	public CommodityReturn() {
	}

	public CommodityReturn(int kod) {
		this.kod = kod;
	}

	public CommodityReturn(int kod, Integer assortmentKod, Integer quantity,
			Integer operationKod, Integer pointKod, Date dateSells,
			Date dateUpdate, Short showPaperWarranty,
			Integer showPaperCommodity, Double amount, Integer serialKod) {
		this.kod = kod;
		this.assortmentKod = assortmentKod;
		this.quantity = quantity;
		this.operationKod = operationKod;
		this.pointKod = pointKod;
		this.dateSells = dateSells;
		this.dateUpdate = dateUpdate;
		this.showPaperWarranty = showPaperWarranty;
		this.showPaperCommodity = showPaperCommodity;
		this.amount = amount;
		this.serialKod = serialKod;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "ASSORTMENT_KOD")
	public Integer getAssortmentKod() {
		return this.assortmentKod;
	}

	public void setAssortmentKod(Integer assortmentKod) {
		this.assortmentKod = assortmentKod;
	}

	@Column(name = "QUANTITY")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "OPERATION_KOD")
	public Integer getOperationKod() {
		return this.operationKod;
	}

	public void setOperationKod(Integer operationKod) {
		this.operationKod = operationKod;
	}

	@Column(name = "POINT_KOD")
	public Integer getPointKod() {
		return this.pointKod;
	}

	public void setPointKod(Integer pointKod) {
		this.pointKod = pointKod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_SELLS", length = 19)
	public Date getDateSells() {
		return this.dateSells;
	}

	public void setDateSells(Date dateSells) {
		this.dateSells = dateSells;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_UPDATE", length = 19)
	public Date getDateUpdate() {
		return this.dateUpdate;
	}

	public void setDateUpdate(Date dateUpdate) {
		this.dateUpdate = dateUpdate;
	}

	@Column(name = "SHOW_PAPER_WARRANTY")
	public Short getShowPaperWarranty() {
		return this.showPaperWarranty;
	}

	public void setShowPaperWarranty(Short showPaperWarranty) {
		this.showPaperWarranty = showPaperWarranty;
	}

	@Column(name = "SHOW_PAPER_COMMODITY")
	public Integer getShowPaperCommodity() {
		return this.showPaperCommodity;
	}

	public void setShowPaperCommodity(Integer showPaperCommodity) {
		this.showPaperCommodity = showPaperCommodity;
	}

	@Column(name = "AMOUNT", precision = 7, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "SERIAL_KOD")
	public Integer getSerialKod() {
		return this.serialKod;
	}

	public void setSerialKod(Integer serialKod) {
		this.serialKod = serialKod;
	}

}
