package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Expenses generated by hbm2java
 */
@Entity
@Table(name = "EXPENSES")
public class Expenses implements java.io.Serializable {

	private int kod;
	private String name;
	private Integer sign;
	private Integer signSeller;
	private String note;

	public Expenses() {
	}

	public Expenses(int kod) {
		this.kod = kod;
	}

	public Expenses(int kod, String name, Integer sign, Integer signSeller,
			String note) {
		this.kod = kod;
		this.name = name;
		this.sign = sign;
		this.signSeller = signSeller;
		this.note = note;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "NAME", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SIGN")
	public Integer getSign() {
		return this.sign;
	}

	public void setSign(Integer sign) {
		this.sign = sign;
	}

	@Column(name = "SIGN_SELLER")
	public Integer getSignSeller() {
		return this.signSeller;
	}

	public void setSignSeller(Integer signSeller) {
		this.signSeller = signSeller;
	}

	@Column(name = "NOTE", length = 50)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
