package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Money generated by hbm2java
 */
@Entity
@Table(name = "MONEY")
public class Money implements java.io.Serializable {

	private int kod;
	private Integer kodPoint;
	private Integer kodExpenses;
	private Integer kodPeople;
	private BigDecimal amount;
	private Date dateInOut;
	private Date dateWrite;
	private String note;
	private Integer kodCommodity;
	private Integer kodAssortment;
	private Integer kodClient;

	public Money() {
	}

	public Money(int kod) {
		this.kod = kod;
	}

	public Money(int kod, Integer kodPoint, Integer kodExpenses,
			Integer kodPeople, BigDecimal amount, Date dateInOut,
			Date dateWrite, String note, Integer kodCommodity,
			Integer kodAssortment, Integer kodClient) {
		this.kod = kod;
		this.kodPoint = kodPoint;
		this.kodExpenses = kodExpenses;
		this.kodPeople = kodPeople;
		this.amount = amount;
		this.dateInOut = dateInOut;
		this.dateWrite = dateWrite;
		this.note = note;
		this.kodCommodity = kodCommodity;
		this.kodAssortment = kodAssortment;
		this.kodClient = kodClient;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "KOD_POINT")
	public Integer getKodPoint() {
		return this.kodPoint;
	}

	public void setKodPoint(Integer kodPoint) {
		this.kodPoint = kodPoint;
	}

	@Column(name = "KOD_EXPENSES")
	public Integer getKodExpenses() {
		return this.kodExpenses;
	}

	public void setKodExpenses(Integer kodExpenses) {
		this.kodExpenses = kodExpenses;
	}

	@Column(name = "KOD_PEOPLE")
	public Integer getKodPeople() {
		return this.kodPeople;
	}

	public void setKodPeople(Integer kodPeople) {
		this.kodPeople = kodPeople;
	}

	@Column(name = "AMOUNT", precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_IN_OUT", length = 10)
	public Date getDateInOut() {
		return this.dateInOut;
	}

	public void setDateInOut(Date dateInOut) {
		this.dateInOut = dateInOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

	@Column(name = "NOTE", length = 50)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "KOD_COMMODITY")
	public Integer getKodCommodity() {
		return this.kodCommodity;
	}

	public void setKodCommodity(Integer kodCommodity) {
		this.kodCommodity = kodCommodity;
	}

	@Column(name = "KOD_ASSORTMENT")
	public Integer getKodAssortment() {
		return this.kodAssortment;
	}

	public void setKodAssortment(Integer kodAssortment) {
		this.kodAssortment = kodAssortment;
	}

	@Column(name = "KOD_CLIENT")
	public Integer getKodClient() {
		return this.kodClient;
	}

	public void setKodClient(Integer kodClient) {
		this.kodClient = kodClient;
	}

}
