package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parameters generated by hbm2java
 */
@Entity
@Table(name = "PARAMETERS")
public class Parameters implements java.io.Serializable {

	private int kod;
	private Date currentDay;
	private String mailUser;
	private String mailPassword;
	private String mailSmtp;
	private Integer mailSmtpPort;
	private String mailDestination;
	private Short mailAuthentification;
	private String offCommand;

	public Parameters() {
	}

	public Parameters(int kod) {
		this.kod = kod;
	}

	public Parameters(int kod, Date currentDay, String mailUser,
			String mailPassword, String mailSmtp, Integer mailSmtpPort,
			String mailDestination, Short mailAuthentification,
			String offCommand) {
		this.kod = kod;
		this.currentDay = currentDay;
		this.mailUser = mailUser;
		this.mailPassword = mailPassword;
		this.mailSmtp = mailSmtp;
		this.mailSmtpPort = mailSmtpPort;
		this.mailDestination = mailDestination;
		this.mailAuthentification = mailAuthentification;
		this.offCommand = offCommand;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CURRENT_DAY", length = 10)
	public Date getCurrentDay() {
		return this.currentDay;
	}

	public void setCurrentDay(Date currentDay) {
		this.currentDay = currentDay;
	}

	@Column(name = "MAIL_USER", length = 50)
	public String getMailUser() {
		return this.mailUser;
	}

	public void setMailUser(String mailUser) {
		this.mailUser = mailUser;
	}

	@Column(name = "MAIL_PASSWORD", length = 50)
	public String getMailPassword() {
		return this.mailPassword;
	}

	public void setMailPassword(String mailPassword) {
		this.mailPassword = mailPassword;
	}

	@Column(name = "MAIL_SMTP", length = 50)
	public String getMailSmtp() {
		return this.mailSmtp;
	}

	public void setMailSmtp(String mailSmtp) {
		this.mailSmtp = mailSmtp;
	}

	@Column(name = "MAIL_SMTP_PORT")
	public Integer getMailSmtpPort() {
		return this.mailSmtpPort;
	}

	public void setMailSmtpPort(Integer mailSmtpPort) {
		this.mailSmtpPort = mailSmtpPort;
	}

	@Column(name = "MAIL_DESTINATION", length = 50)
	public String getMailDestination() {
		return this.mailDestination;
	}

	public void setMailDestination(String mailDestination) {
		this.mailDestination = mailDestination;
	}

	@Column(name = "MAIL_AUTHENTIFICATION")
	public Short getMailAuthentification() {
		return this.mailAuthentification;
	}

	public void setMailAuthentification(Short mailAuthentification) {
		this.mailAuthentification = mailAuthentification;
	}

	@Column(name = "OFF_COMMAND", length = 50)
	public String getOffCommand() {
		return this.offCommand;
	}

	public void setOffCommand(String offCommand) {
		this.offCommand = offCommand;
	}

}
