package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatternOfInput generated by hbm2java
 */
@Entity
@Table(name = "PATTERN_OF_INPUT")
public class PatternOfInput implements java.io.Serializable {

	private int kod;
	private String name;
	private Integer position;

	public PatternOfInput() {
	}

	public PatternOfInput(int kod) {
		this.kod = kod;
	}

	public PatternOfInput(int kod, String name, Integer position) {
		this.kod = kod;
		this.name = name;
		this.position = position;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "POSITION")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

}
