package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PeoplePoint generated by hbm2java
 */
@Entity
@Table(name = "PEOPLE_POINT")
public class PeoplePoint implements java.io.Serializable {

	private int kod;
	private Integer kodPeople;
	private Integer kodPoint;
	private Double percent;
	private Double percentIncrease;

	public PeoplePoint() {
	}

	public PeoplePoint(int kod) {
		this.kod = kod;
	}

	public PeoplePoint(int kod, Integer kodPeople, Integer kodPoint,
			Double percent, Double percentIncrease) {
		this.kod = kod;
		this.kodPeople = kodPeople;
		this.kodPoint = kodPoint;
		this.percent = percent;
		this.percentIncrease = percentIncrease;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "KOD_PEOPLE")
	public Integer getKodPeople() {
		return this.kodPeople;
	}

	public void setKodPeople(Integer kodPeople) {
		this.kodPeople = kodPeople;
	}

	@Column(name = "KOD_POINT")
	public Integer getKodPoint() {
		return this.kodPoint;
	}

	public void setKodPoint(Integer kodPoint) {
		this.kodPoint = kodPoint;
	}

	@Column(name = "PERCENT", precision = 7, scale = 0)
	public Double getPercent() {
		return this.percent;
	}

	public void setPercent(Double percent) {
		this.percent = percent;
	}

	@Column(name = "PERCENT_INCREASE", precision = 7, scale = 0)
	public Double getPercentIncrease() {
		return this.percentIncrease;
	}

	public void setPercentIncrease(Double percentIncrease) {
		this.percentIncrease = percentIncrease;
	}

}
