package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * People generated by hbm2java
 */
@Entity
@Table(name = "PEOPLE")
public class People implements java.io.Serializable {

	private int kod;
	private String name;
	private Integer kodPost;
	private String keyKod;
	private Short isHide;
	private Double percent;

	public People() {
	}

	public People(int kod) {
		this.kod = kod;
	}

	public People(int kod, String name, Integer kodPost, String keyKod,
			Short isHide, Double percent) {
		this.kod = kod;
		this.name = name;
		this.kodPost = kodPost;
		this.keyKod = keyKod;
		this.isHide = isHide;
		this.percent = percent;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "KOD_POST")
	public Integer getKodPost() {
		return this.kodPost;
	}

	public void setKodPost(Integer kodPost) {
		this.kodPost = kodPost;
	}

	@Column(name = "KEY_KOD", length = 50)
	public String getKeyKod() {
		return this.keyKod;
	}

	public void setKeyKod(String keyKod) {
		this.keyKod = keyKod;
	}

	@Column(name = "IS_HIDE")
	public Short getIsHide() {
		return this.isHide;
	}

	public void setIsHide(Short isHide) {
		this.isHide = isHide;
	}

	@Column(name = "PERCENT", precision = 7, scale = 0)
	public Double getPercent() {
		return this.percent;
	}

	public void setPercent(Double percent) {
		this.percent = percent;
	}

}
