package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "PHOTO")
public class Photo implements java.io.Serializable {

	private int id;
	private String filename;
	private String fullName;
	private String httpPath;

	public Photo() {
	}

	public Photo(int id) {
		this.id = id;
	}

	public Photo(int id, String filename, String fullName, String httpPath) {
		this.id = id;
		this.filename = filename;
		this.fullName = fullName;
		this.httpPath = httpPath;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "FILENAME")
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "FULL_NAME")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "HTTP_PATH")
	public String getHttpPath() {
		return this.httpPath;
	}

	public void setHttpPath(String httpPath) {
		this.httpPath = httpPath;
	}

}
