package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PriceTempId generated by hbm2java
 */
@Embeddable
public class PriceTempId implements java.io.Serializable {

	private int kod;
	private BigDecimal priceBuying;
	private BigDecimal price;
	private Short valid;
	private String note;
	private Date dateWrite;
	private Integer nextKod;

	public PriceTempId() {
	}

	public PriceTempId(int kod) {
		this.kod = kod;
	}

	public PriceTempId(int kod, BigDecimal priceBuying, BigDecimal price,
			Short valid, String note, Date dateWrite, Integer nextKod) {
		this.kod = kod;
		this.priceBuying = priceBuying;
		this.price = price;
		this.valid = valid;
		this.note = note;
		this.dateWrite = dateWrite;
		this.nextKod = nextKod;
	}

	@Column(name = "KOD", nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "PRICE_BUYING", precision = 15)
	public BigDecimal getPriceBuying() {
		return this.priceBuying;
	}

	public void setPriceBuying(BigDecimal priceBuying) {
		this.priceBuying = priceBuying;
	}

	@Column(name = "PRICE", precision = 15)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "VALID")
	public Short getValid() {
		return this.valid;
	}

	public void setValid(Short valid) {
		this.valid = valid;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

	@Column(name = "NEXT_KOD")
	public Integer getNextKod() {
		return this.nextKod;
	}

	public void setNextKod(Integer nextKod) {
		this.nextKod = nextKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PriceTempId))
			return false;
		PriceTempId castOther = (PriceTempId) other;

		return (this.getKod() == castOther.getKod())
				&& ((this.getPriceBuying() == castOther.getPriceBuying()) || (this
						.getPriceBuying() != null
						&& castOther.getPriceBuying() != null && this
						.getPriceBuying().equals(castOther.getPriceBuying())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getValid() == castOther.getValid()) || (this
						.getValid() != null && castOther.getValid() != null && this
						.getValid().equals(castOther.getValid())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())))
				&& ((this.getDateWrite() == castOther.getDateWrite()) || (this
						.getDateWrite() != null
						&& castOther.getDateWrite() != null && this
						.getDateWrite().equals(castOther.getDateWrite())))
				&& ((this.getNextKod() == castOther.getNextKod()) || (this
						.getNextKod() != null && castOther.getNextKod() != null && this
						.getNextKod().equals(castOther.getNextKod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKod();
		result = 37
				* result
				+ (getPriceBuying() == null ? 0 : this.getPriceBuying()
						.hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result
				+ (getValid() == null ? 0 : this.getValid().hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result
				+ (getDateWrite() == null ? 0 : this.getDateWrite().hashCode());
		result = 37 * result
				+ (getNextKod() == null ? 0 : this.getNextKod().hashCode());
		return result;
	}

}
