package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PriceTemp generated by hbm2java
 */
@Entity
@Table(name = "PRICE_TEMP")
public class PriceTemp implements java.io.Serializable {

	private PriceTempId id;

	public PriceTemp() {
	}

	public PriceTemp(PriceTempId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "kod", column = @Column(name = "KOD", nullable = false)),
			@AttributeOverride(name = "priceBuying", column = @Column(name = "PRICE_BUYING", precision = 15)),
			@AttributeOverride(name = "price", column = @Column(name = "PRICE", precision = 15)),
			@AttributeOverride(name = "valid", column = @Column(name = "VALID")),
			@AttributeOverride(name = "note", column = @Column(name = "NOTE")),
			@AttributeOverride(name = "dateWrite", column = @Column(name = "DATE_WRITE", length = 19)),
			@AttributeOverride(name = "nextKod", column = @Column(name = "NEXT_KOD")) })
	public PriceTempId getId() {
		return this.id;
	}

	public void setId(PriceTempId id) {
		this.id = id;
	}

}
