package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "PRICE")
public class Price implements java.io.Serializable {

	private int kod;
	private BigDecimal priceBuying;
	private BigDecimal price;
	private Short valid;
	private String note;
	private Date dateWrite;
	private Integer nextKod;

	public Price() {
	}

	public Price(int kod) {
		this.kod = kod;
	}

	public Price(int kod, BigDecimal priceBuying, BigDecimal price,
			Short valid, String note, Date dateWrite, Integer nextKod) {
		this.kod = kod;
		this.priceBuying = priceBuying;
		this.price = price;
		this.valid = valid;
		this.note = note;
		this.dateWrite = dateWrite;
		this.nextKod = nextKod;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "PRICE_BUYING", precision = 15)
	public BigDecimal getPriceBuying() {
		return this.priceBuying;
	}

	public void setPriceBuying(BigDecimal priceBuying) {
		this.priceBuying = priceBuying;
	}

	@Column(name = "PRICE", precision = 15)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "VALID")
	public Short getValid() {
		return this.valid;
	}

	public void setValid(Short valid) {
		this.valid = valid;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

	@Column(name = "NEXT_KOD")
	public Integer getNextKod() {
		return this.nextKod;
	}

	public void setNextKod(Integer nextKod) {
		this.nextKod = nextKod;
	}

}
