package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rediscount generated by hbm2java
 */
@Entity
@Table(name = "REDISCOUNT")
public class Rediscount implements java.io.Serializable {

	private Integer kod;
	private Short isSource;
	private Integer kodPoint;
	private Date dateRediscount;
	private Integer kodAssortment;
	private Integer kodSerial;
	private Date dateWrite;

	public Rediscount() {
	}

	public Rediscount(int kod) {
		this.kod = kod;
	}

	public Rediscount(int kod, Short isSource, Integer kodPoint,
			Date dateRediscount, Integer kodAssortment, Integer kodSerial,
			Date dateWrite) {
		this.kod = kod;
		this.isSource = isSource;
		this.kodPoint = kodPoint;
		this.dateRediscount = dateRediscount;
		this.kodAssortment = kodAssortment;
		this.kodSerial = kodSerial;
		this.dateWrite = dateWrite;
	}

	@Id
	@Column(name = "KOD")
	@SequenceGenerator(name="generator",sequenceName="GEN_REDISCOUNT_ID")
	@GeneratedValue(generator="generator",strategy=GenerationType.AUTO)
	public Integer getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "IS_SOURCE")
	public Short getIsSource() {
		return this.isSource;
	}

	public void setIsSource(Short isSource) {
		this.isSource = isSource;
	}

	@Column(name = "KOD_POINT")
	public Integer getKodPoint() {
		return this.kodPoint;
	}

	public void setKodPoint(Integer kodPoint) {
		this.kodPoint = kodPoint;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_REDISCOUNT", length = 10)
	public Date getDateRediscount() {
		return this.dateRediscount;
	}

	public void setDateRediscount(Date dateRediscount) {
		this.dateRediscount = dateRediscount;
	}

	@Column(name = "KOD_ASSORTMENT")
	public Integer getKodAssortment() {
		return this.kodAssortment;
	}

	public void setKodAssortment(Integer kodAssortment) {
		this.kodAssortment = kodAssortment;
	}

	@Column(name = "KOD_SERIAL")
	public Integer getKodSerial() {
		return this.kodSerial;
	}

	public void setKodSerial(Integer kodSerial) {
		this.kodSerial = kodSerial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

}
