package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reminder generated by hbm2java
 */
@Entity
@Table(name = "REMINDER")
public class Reminder implements java.io.Serializable {

	private int kod;
	private Integer pointsKod;
	private String note;
	private Date outDate;
	private Date inDate;
	private Short flagDelete;

	public Reminder() {
	}

	public Reminder(int kod) {
		this.kod = kod;
	}

	public Reminder(int kod, Integer pointsKod, String note, Date outDate,
			Date inDate, Short flagDelete) {
		this.kod = kod;
		this.pointsKod = pointsKod;
		this.note = note;
		this.outDate = outDate;
		this.inDate = inDate;
		this.flagDelete = flagDelete;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "POINTS_KOD")
	public Integer getPointsKod() {
		return this.pointsKod;
	}

	public void setPointsKod(Integer pointsKod) {
		this.pointsKod = pointsKod;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OUT_DATE", length = 19)
	public Date getOutDate() {
		return this.outDate;
	}

	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IN_DATE", length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	@Column(name = "FLAG_DELETE")
	public Short getFlagDelete() {
		return this.flagDelete;
	}

	public void setFlagDelete(Short flagDelete) {
		this.flagDelete = flagDelete;
	}

}
