package com.cherkashyn.vitalii.computer_shop.rediscount.domain;

// Generated 14.09.2013 14:22:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serial generated by hbm2java
 */
@Entity
@Table(name = "SERIAL")
public class Serial implements java.io.Serializable {

	private int kod;
	private String number;
	private String numberSeller;
	private Date dateWrite;

	public Serial() {
	}

	public Serial(int kod) {
		this.kod = kod;
	}

	public Serial(int kod, String number, String numberSeller, Date dateWrite) {
		this.kod = kod;
		this.number = number;
		this.numberSeller = numberSeller;
		this.dateWrite = dateWrite;
	}

	@Id
	@Column(name = "KOD", unique = true, nullable = false)
	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	@Column(name = "NUMBER", length = 30)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "NUMBER_SELLER", length = 30)
	public String getNumberSeller() {
		return this.numberSeller;
	}

	public void setNumberSeller(String numberSeller) {
		this.numberSeller = numberSeller;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_WRITE", length = 19)
	public Date getDateWrite() {
		return this.dateWrite;
	}

	public void setDateWrite(Date dateWrite) {
		this.dateWrite = dateWrite;
	}

}
